### ISSUE TITLE
installing contrib results in version: `neptune-contrib==0+unknown`

### ISSUE THREAD

**Issue by kamil-kaczmarek** [neptune-ai/neptune-contrib#109]
Installing via pip, as a result I have a version

`neptune-contrib==0+unknown`

**Comment by kamil-kaczmarek** [comment]
Also, we have - in the README.md -> docs failing and build failing.

@jakubczakon I think that this should be arranged for some fixes :)

**Comment by PiotrJander** [comment]
I can confirm that versions 0.24.2 and 0.24.3 of `neptune-contrib` are visible as having version `0+unknow`.

However, when I build an sdist or a wheel locally, and install it, the version is shown correctly.

Not sure what to do about this.

**Comment by kamil-kaczmarek** [comment]
In my virtualenv I see ony `0+unknown`.

Simply speaking I think it should display correct version in the virtual env.

@PiotrJander do oyu have any ideas how to solve it?

**Comment by kamil-kaczmarek** [comment]
Issue is related to the versioneer (https://github.com/neptune-ai/neptune-contrib/blob/master/neptunecontrib/_version.py#L209).

**Comment by PiotrJander** [comment]
Fixed
