### ISSUE TITLE
CI on master fails

### ISSUE THREAD

**Issue by kamil-kaczmarek** [neptune-ai/neptune-contrib#112]
Wanted to report that CI on master is failing: https://github.com/neptune-ai/neptune-contrib/runs/1320168058#step:6:15

@PiotrJander can you have a look?

**Comment by PiotrJander** [comment]
I fixed some problems, but the publishing step still fails because of invalid PyPI credentials - we should have a look at this (perhaps with @jakubczakon ) together

**Comment by PiotrJander** [comment]
Fixed now
