### ISSUE TITLE
model and feature importance are not logged for xgboost regressor

### ISSUE THREAD

**Issue by jakubczakon** [neptune-ai/neptune-contrib#114]
When running logging for xgboost regressor with Neptune integration the following happens:

- metrics get logged (and charts created)
- model checkpoint is not logged after iteration or training
- feature importance is not logged after iteration or training

Code examples:
- code + experiment [with problem](https://ui.neptune.ai/o/shared/org/showroom/e/SHOW-2078/source-code?path=.&file=debug_xgboost.py
)
- code + experiment [without the problem 
](https://ui.neptune.ai/o/shared/org/XGBoost-integration/e/XGB-5868/logs)

**Comment by kamil-kaczmarek** [comment]
added in new integration
