### ISSUE TITLE
parameters: 'None', 'False', 'True'

### ISSUE THREAD

**Issue by wjaskowski** [neptune-ai/neptune-contrib#56]
The parameter values of None, False and True get converted to strings of 'None', 'False' and 'True' when downloaded `neptune.get_experiment()`. Easy to work-around but irritating.

I am not sure whether this is NeptuneObserver issue or Neptune issue since I am working solely with sacred.

**Comment by kamil-kaczmarek** [comment]
Hi @wjaskowski,

This is related to the neptune-client. When creating parameters we can recognize floats. Everything else is converted to string.

I assume that you request to also recognize Boolean and None values :slightly_smiling_face: 

Best,
Kamil

**Comment by wjaskowski** [comment]
I think you should recognize ints as well. Weird to see I have 8.0 layers.
Take a look what sacred recognizes. I've never had problems with its
conversions.

This is a tiny issue obviously.

**Comment by kamil-kaczmarek** [comment]
Hey, thanks for further clarifications. I'll look how sacred is doing this.

Best,
Kamil
